root: true
env:
  browser: true
  node: true
plugins":
  - 'import'
  - 'unused-imports'
extends:
  - '@nuxtjs'
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:prettier/recommended'
  - 'plugin:nuxt/recommended'
